-- Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User holdings (replaces hardcoded config)
CREATE TABLE IF NOT EXISTS user_holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    symbol TEXT NOT NULL,
    shares NUMERIC NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User margin loans (replaces hardcoded config)
CREATE TABLE IF NOT EXISTS user_margin_loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    label TEXT NOT NULL,
    currency TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS policies: allow anon key full access (personal dashboard)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_holdings ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_margin_loans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_all_users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "anon_all_user_holdings" ON user_holdings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "anon_all_user_margin_loans" ON user_margin_loans FOR ALL USING (true) WITH CHECK (true);
